all:
    vars:
        ansible_connection: lxd
        ansible_user: root
        ansible_become: no
    children:
        local:
            vars:
                ansible_lxd_remote: local
                # ansible_lxd_project: demo
            hosts:
                c1:
                v1:
        stm32:
            vars:
                ansible_lxd_remote: local
            hosts:
                stm32dev:


